Repository msazurestackworkloads/azurestack-gallery, pull requests merged in 2019-03, with the labels that each got.

#23 Remove blob disk option from storage profile.
  kubernetes/template/DeploymentTemplates/MainTemplate.json
  kubernetes/template/DeploymentTemplates/azuredeploy.json
  kubernetes/template/DeploymentTemplates/createUiDefinition.json
Labels: enhancement

#22 Removing Blob disk option from storage profile option.
  kubernetes/template/DeploymentTemplates/MainTemplate.json
  kubernetes/template/DeploymentTemplates/azuredeploy.json
  kubernetes/template/DeploymentTemplates/createUiDefinition.json
Labels: bug, enhancement

#30 Remove any SPN ID logging done from azure CLI
  kubernetes/template/DeploymentTemplates/azuredeploy.json
  kubernetes/template/DeploymentTemplates/script.sh
Labels: bug

#36 SSH config restore fails if temp file not is created
  diagnosis/getkuberneteslogs.sh
Labels: bug

#38 Forgot to download hosts.sh
  diagnosis/getkuberneteslogs.sh
Labels: bug
